### ISSUE TITLE
[Model] YOLOv3

### ISSUE THREAD

**Issue by hics33** [KerasKorea/KerasObjectDetector#12]
### Finding repository for reference

- https://github.com/qqwweee/keras-yolo3
This seems good for reference because this is popular and works well when I tested this on sample images.
In addtion, this provides method to convert Darknet model to Keras model, so we can use Darknet model for this through conversion.

- Other options
https://github.com/experiencor/keras-yolo3
https://github.com/xiaochus/YOLOv3 : no training module
Darknet weights can be used for these implementations as qqwweee's

**Comment by MijeongJeon** [comment]
We selected **https://github.com/qqwweee/keras-yolo3**
