### ISSUE TITLE
[Preprocessing] Dataset - COCO

### ISSUE THREAD

**Issue by simba328** [KerasKorea/KerasObjectDetector#14]
- [x] Explanation of the dataset
- [x] Download dataset 
~~[ ] Generate generator~~
~~[ ] Process label map~~

**Comment by MijeongJeon** [comment]
http://bit.ly/yolk_coco_test2017_zip 
http://bit.ly/yolk_coco_train2017_zip
http://bit.ly/yolk_coco_val2017_zip

**Comment by MijeongJeon** [comment]
http://bit.ly/yolk_coco_annotation2017_zip

@simba328 I updated train and test file and uploaded annotation.zip. Thanks!
