### ISSUE TITLE
Finding fancy module name! 

### ISSUE THREAD

**Issue by visionNoob** [KerasKorea/KerasObjectDetector#19]
Any idea?

**Comment by MijeongJeon** [comment]
How about `kekoDetector`?
It means KerasKorea's Detector. kekeke

**Comment by MijeongJeon** [comment]
test

**Comment by mike2ox** [comment]
Umm... `KOD(keras object detection)`? or `KatzeBox(german means cat box)`

**Comment by SooDevv** [comment]
Previously, we decided temporarily module name KerasObjectDetector!
