### ISSUE TITLE
Small dataset 

### ISSUE THREAD

**Issue by visionNoob** [KerasKorea/KerasObjectDetector#27]
I think it's better to provide a variety of small datasets for uesrs. 
When we try to design our own model, the first thing to do is to overfit our model with very small dataset. When overfitting(training process) is done, we could guess our model has no bug. Although its a very good debugging strategy, It's too annoying to make another small dataset. so I think when we provide small dataset (e.g. small voc, small coco), many people might feel useful.

**Comment by MijeongJeon** [comment]
It's a very nice idea. I think everyone need that small dataset!
What percentage of the data is appropriate?
How about 20% ~ 50% of the total dataset?

Small data makes many people happy 🥳

**Comment by MijeongJeon** [comment]
Make an option in `DataGenerator`
