### ISSUE TITLE
[Utils-Visualization] Make classes box colorful 

### ISSUE THREAD

**Issue by MijeongJeon** [KerasKorea/KerasObjectDetector#7]
### Make classes boxes have their own color

* Show various colors to multi-class for box bounding

- work branch : `utils-visualization_colors`

**Comment by melonicedlatte** [comment]
I make first image color randomly maker. If there is a problem, please comment!

**Comment by melonicedlatte** [comment]
Now, i push make boxex using matplotlib. You can confirm using test_plt.py.
